<div class="contentItem">
    <div class="contentTitle"><?php echo $this->position->get_company(); ?></div>
    <div class="rightSide de-emphasize"><?php echo $this->position->get_location(); ?></div>
    <div class="rightSide de-emphasize"><?php echo $this->position->get_startdate(); ?>&ndash;<?php echo $this->position->get_enddate(); ?></div>
    <div class="contentSubtitle"><?php echo $this->position->get_title(); ?></div>
    <div class="content"><?php echo $this->position->get_content(); ?></div>
</div>