<div class="contentItem">
    <div class="contentTitle"><?php echo $this->project->get_title(); ?></div>
    <div class="rightSide de-emphasize"><?php echo $this->project->get_location(); ?></div>
    <div class="rightSide de-emphasize"><?php echo $this->project->get_startdate(); ?>&ndash;<?php echo $this->project->get_enddate(); ?></div>
    <div class="contentSubtitle"><?php echo $this->project->get_url(); ?></div>
    <div class="content"><?php echo $this->project->get_content(); ?></div>
</div>