<div id="summary">
    <?php echo $this->translate('summary'); ?>
</div>
<div id="contactsummary">
    <?php echo $this->translate('contactsummary'); ?>
</div>
<a href="http://www.linkedin.com/in/dimosthenisnikoudis" id="linkedinlink" class="profilelink">LinkedIn</a>
<a href="http://www.facebook.com/profile.php?id=100000908538039" id="facebooklink" class="profilelink">Facebook</a>
<a href="https://plus.google.com/105187660019247469517" id="googlepluslink" class="profilelink">Google+</a>