<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <title><?php echo $this->translate($this->pageTitle); ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="alternate" hreflang="en" href="http://en.dnna.gr/" />
        <link rel="alternate" hreflang="el" href="http://el.dnna.gr/" />
        <?php echo $this->headLink()."\n"; ?>
        <?php echo $this->headMeta()."\n"; ?>
    </head>
    <body>
        <?php echo $this->layout()->content ?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <?php echo $this->headScript(); ?>
    </body>
</html>