<?php $this->headScript()->appendFile($this->baseUrl('js/main.js')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/global.css'), 'screen, print'); ?>
<?php $this->headMeta()->appendName('Description', $this->translate('mainpagedescr')); ?>
<div id="page">
    <h1><?php echo $this->translate($this->pageTitle); ?></h1>
    <h2><?php echo $this->translate('softeng'); ?></h2>
    <nav>
        <?php $this->navigation()->menu()->renderMenu(null,array('maxDepth' => 0)); ?>
        <?php $this->navigation()->menu()->setPartial('partials/navigation.phtml'); ?>
        <?php echo $this->navigation()->menu()->render(); ?>
    </nav>
    <div id="languagebar">
        <?php foreach ($this->languages as $curCode => $curLanguage) { ?>
            <div class="language"><a href="<?php echo $this->getLanguageLink($curCode); ?>"><?php echo $curLanguage; ?></a></div>
        <?php } ?>
    </div>
    <div id="tabs-container">
        <?php echo $this->content; ?>
    </div>
    <footer>
        <a href="<?php echo $this->baseUrl('dnikoudis.vcf'); ?>"><?php echo $this->translate('vard'); ?></a> | 
        <a href="<?php echo $this->url(array('module' => 'cv', 'controller' => 'index')); ?>"><?php echo $this->translate('cv'); ?></a> | 
        <a href="http://code.google.com/u/dnna@dnna.gr/"><?php echo $this->translate('gcodeprofile'); ?></a>
    </footer>
</div>